import { Injectable, Logger, OnModuleInit } from '@nestjs/common'
import { DatabaseService } from '../../../Common_Pages/database/database.service'
import { MailService } from '../../../Common_Pages/mail/mail.service'
import { NotificationsService } from '../../../Common_Pages/notifications/notifications.service'

// The status set on a project + valuation once a technical officer is assigned.
const TO_ASSIGNED = 'Technical Officer Assigned'

// SQL that upgrades an old valuations table to the new shape (surrogate `id`
// primary key + per-project integer `valuation_id`). Safe to run repeatedly.
const MIGRATION = `
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'valuations' AND column_name = 'id'
  ) THEN
    ALTER TABLE valuations DROP CONSTRAINT IF EXISTS valuations_pkey;
    ALTER TABLE valuations ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'valuations' AND column_name = 'valuation_id'
      AND data_type <> 'integer'
  ) THEN
    ALTER TABLE valuations ALTER COLUMN valuation_id DROP DEFAULT;
    WITH ranked AS (
      SELECT id, ROW_NUMBER() OVER (PARTITION BY project_id ORDER BY created_at, id) AS rn
        FROM valuations
    )
    UPDATE valuations v SET valuation_id = ranked.rn::text
      FROM ranked WHERE ranked.id = v.id;
    ALTER TABLE valuations ALTER COLUMN valuation_id TYPE INTEGER USING valuation_id::integer;
    ALTER TABLE valuations ALTER COLUMN valuation_id SET DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valuations_project_no_unique'
  ) THEN
    ALTER TABLE valuations
      ADD CONSTRAINT valuations_project_no_unique UNIQUE (project_id, valuation_id);
  END IF;
END $$;`

// Creates and reads valuations. Each valuation belongs to a project; its
// `valuation_id` counts how many times that project/land has been valued.
@Injectable()
export class ValuationsService implements OnModuleInit {
  private readonly logger = new Logger(ValuationsService.name)

  constructor(
    private readonly db: DatabaseService,
    private readonly mail: MailService,
    private readonly notifications: NotificationsService,
  ) {}

  // Make sure the columns/keys this service needs exist (safe to re-run).
  async onModuleInit() {
    const columns = [
      `status VARCHAR(40) NOT NULL DEFAULT 'Created'`,
      `request_letter_path VARCHAR(255) NOT NULL DEFAULT ''`,
      `technical_officer_id VARCHAR(20) NOT NULL DEFAULT ''`,
    ]
    for (const def of columns) {
      try {
        await this.db.query(`ALTER TABLE valuations ADD COLUMN IF NOT EXISTS ${def}`)
      } catch (err) {
        this.logger.error(`Could not ensure valuation column: ${(err as Error).message}`)
      }
    }
    try {
      await this.db.query(MIGRATION)
    } catch (err) {
      this.logger.error(`Valuation migration failed: ${(err as Error).message}`)
    }
  }

  async create(body: { projectId?: string; applicantNic?: string; data?: string }, file?: Express.Multer.File) {
    const projectId = (body.projectId ?? '').trim()
    // valuation_id = (highest number this project already has) + 1.
    const result = await this.db.query(
      `INSERT INTO valuations (valuation_id, project_id, applicant_nic, details, request_letter_path)
       VALUES (
         (SELECT COALESCE(MAX(valuation_id), 0) + 1 FROM valuations WHERE project_id = $1),
         $1, $2, $3::jsonb, $4
       )
       RETURNING id, valuation_id`,
      [projectId, (body.applicantNic ?? '').trim(), body.data || '{}', file?.filename ?? ''],
    )
    await this.notifyValuationRequested(
      projectId,
      (body.applicantNic ?? '').trim(),
      body.data || '{}',
    )
    return {
      rowId: Number(result.rows[0].id),
      valuationId: Number(result.rows[0].valuation_id),
    }
  }

  // Project-status milestone: a valuation request has been raised. Notify the
  // applicant and only the bank branch linked to this valuation.
  private async notifyValuationRequested(projectId: string, nic: string, dataJson: string) {
    try {
      let details: Record<string, unknown> = {}
      try { details = JSON.parse(dataJson) as Record<string, unknown> } catch { /* empty */ }
      if (nic) {
        await this.notifications.create(
          nic,
          `A valuation request has been created for project ${projectId}. A technical officer will be assigned next.`,
        )
      }
      const branchCode = String(details.bankBranchCode ?? '').trim()
      const bankEmail = String(details.bankEmail ?? '').trim()
      const bankUserId = branchCode || (bankEmail
        ? await this.notifications.resolveBankUserId(bankEmail)
        : null)
      if (bankUserId) {
        await this.notifications.create(
          bankUserId,
          `The valuation request for project ${projectId} has been created. A technical officer will be assigned next.`,
        )
      }
    } catch (err) {
      this.logger.error(`Valuation-request notification failed: ${(err as Error).message}`)
    }
  }

  // The technical officers a coordinator can assign a valuation to — only
  // those who are actually free (not already assigned open work, and not on
  // leave today). Kept in sync with the same availability rule used by Fleet
  // Management (see FleetService.officers()).
  async listTechnicalOfficers() {
    const r = await this.db.query(
      `SELECT user_id, first_name, last_name, email
         FROM users
        WHERE role = 'Technical Officer'
          AND user_id NOT IN (
            SELECT technical_officer_id FROM valuations
             WHERE status = $1 AND technical_officer_id <> '')
          AND user_id NOT IN (
            SELECT to_id FROM to_leaves WHERE leave_date = CURRENT_DATE OR leave_date IS NULL)
        ORDER BY first_name, last_name`,
      [TO_ASSIGNED],
    )
    return r.rows.map((row) => ({
      userId: row.user_id as string,
      name: `${row.first_name} ${row.last_name}`,
      email: row.email as string,
    }))
  }

  // Assign a technical officer to a valuation. Updates the valuation + project
  // status and notifies the loan applicant and the requesting bank.
  async assignTechnicalOfficer(rowId: string, technicalOfficerId: string) {
    const n = Number(rowId)
    if (!Number.isInteger(n)) return { ok: false, error: 'Invalid valuation.' }
    const toId = (technicalOfficerId ?? '').trim()
    if (!toId) return { ok: false, error: 'Please select a technical officer.' }

    const v = await this.db.query(
      `UPDATE valuations
          SET technical_officer_id = $1, status = $2
        WHERE id = $3
        RETURNING project_id, valuation_id, applicant_nic`,
      [toId, TO_ASSIGNED, n],
    )
    const row = v.rows[0]
    if (!row) return { ok: false, error: 'Valuation not found.' }
    const projectId = row.project_id as string

    // The project's status now reflects the assignment too.
    await this.db.query(`UPDATE projects SET status = $1 WHERE project_id = $2`, [
      TO_ASSIGNED,
      projectId,
    ])

    await this.notifyAssigned(projectId, row.applicant_nic as string, toId)

    return { ok: true, projectId, valuationId: Number(row.valuation_id) }
  }

  // Emails + in-system notifies the assigned officer, the loan applicant and
  // the requesting bank about the assignment.
  private async notifyAssigned(projectId: string, nic: string, toId: string) {
    try {
      const proj = await this.db.query(
        `SELECT bank_email FROM projects WHERE project_id = $1 LIMIT 1`,
        [projectId],
      )
      const bankEmail = (proj.rows[0]?.bank_email as string) ?? ''

      const appl = await this.db.query(
        `SELECT email FROM users WHERE nic = $1 AND role = 'Loan Applicant' LIMIT 1`,
        [nic],
      )
      const applicantEmail = (appl.rows[0]?.email as string) ?? ''

      const to = await this.db.query(
        `SELECT first_name, last_name FROM users WHERE user_id = $1 LIMIT 1`,
        [toId],
      )
      const officerName = to.rows[0]
        ? `${to.rows[0].first_name} ${to.rows[0].last_name}`
        : toId

      // In-system notification to the officer — this is the action item.
      await this.notifications.create(
        toId,
        `You have been assigned to project ${projectId} for a site inspection. Please review the project details and schedule your visit.`,
      )

      if (applicantEmail) {
        await this.mail.sendTechnicalOfficerAssigned(applicantEmail, {
          projectId, officerName, audience: 'applicant',
        })
      }
      await this.notifications.create(
        nic,
        `A technical officer (${officerName}) has been assigned to inspect the property for project ${projectId}.`,
      )

      if (bankEmail) {
        await this.mail.sendTechnicalOfficerAssigned(bankEmail, {
          projectId, officerName, audience: 'bank',
        })
        const bankUserId = await this.notifications.resolveBankUserId(bankEmail)
        if (bankUserId) {
          await this.notifications.create(
            bankUserId,
            `A technical officer has been assigned to inspect the property for project ${projectId}.`,
          )
        }
      }
    } catch (err) {
      this.logger.error(`Assignment notification failed: ${(err as Error).message}`)
    }
  }

  // All valuations for one project, in order (1st, 2nd, ...).
  async listByProject(projectId: string) {
    const r = await this.db.query(
      `SELECT id, valuation_id, project_id, status, created_at
         FROM valuations
        WHERE project_id = $1
        ORDER BY valuation_id ASC`,
      [projectId.trim()],
    )
    return r.rows.map((row) => ({
      rowId: Number(row.id),
      valuationId: Number(row.valuation_id),
      projectId: row.project_id as string,
      status: row.status as string,
      createdAt: row.created_at as string,
    }))
  }

  // The full saved details of one valuation (every field the coordinator filled),
  // plus meta. Used to view an existing valuation from the New Valuation lookup.
  async details(rowId: string) {
    const n = Number(rowId)
    if (!Number.isInteger(n)) return null
    const r = await this.db.query(
      `SELECT id, valuation_id, project_id, applicant_nic, status, details,
              request_letter_path, created_at
         FROM valuations WHERE id = $1 LIMIT 1`,
      [n],
    )
    const row = r.rows[0]
    if (!row) return null
    const details =
      typeof row.details === 'string' ? JSON.parse(row.details || '{}') : (row.details ?? {})
    return {
      rowId: Number(row.id),
      valuationId: Number(row.valuation_id),
      projectId: row.project_id as string,
      nic: row.applicant_nic as string,
      status: row.status as string,
      details: details as Record<string, string>,
      hasRequestLetter: !!(row.request_letter_path as string),
      createdAt: row.created_at as string,
    }
  }

  // The stored request-letter filename for a valuation (for file streaming).
  async requestLetterPath(rowId: string) {
    const n = Number(rowId)
    if (!Number.isInteger(n)) return null
    const r = await this.db.query(
      `SELECT request_letter_path FROM valuations WHERE id = $1 LIMIT 1`,
      [n],
    )
    const p = r.rows[0]?.request_letter_path as string | undefined
    return p ? p : null
  }

  // Every valuation raised for an applicant (across all their projects). Used by
  // the New Valuation lookup to show any existing valuations for a NIC.
  async listByNic(nic: string) {
    const r = await this.db.query(
      `SELECT v.id, v.valuation_id, v.project_id, v.status, v.created_at
         FROM valuations v
         JOIN projects p ON p.project_id = v.project_id
        WHERE p.applicant_nic = $1
        ORDER BY v.valuation_id ASC`,
      [nic.trim()],
    )
    return r.rows.map((row) => ({
      rowId: Number(row.id),
      valuationId: Number(row.valuation_id),
      projectId: row.project_id as string,
      status: row.status as string,
      createdAt: row.created_at as string,
    }))
  }

  // Compute the full project-status lifecycle from the actual data.
  // `hasValuation`/`toAssigned` come from the specific (or latest) valuation;
  // the rest are project-level. Shown to every role on the shared Project
  // Status page (applicant, bank, coordinator, technical officer, managers).
  private async computeSteps(projectId: string, nic: string, hasValuation: boolean, toAssigned: boolean) {
    const has = async (sql: string, params: unknown[]) => (await this.db.query(sql, params)).rows.length > 0
    const applicant = await has(`SELECT 1 FROM users WHERE nic = $1 AND role = 'Loan Applicant' LIMIT 1`, [nic])
    const inspection = hasValuation && (await has(`SELECT 1 FROM inspections WHERE project_id = $1 LIMIT 1`, [projectId]))
    const dr = await this.db.query(`SELECT review_status, paid, slip_pending FROM drafts WHERE project_id = $1`, [projectId])
    const draft = hasValuation
      ? (dr.rows[0] as { review_status?: string; paid?: boolean; slip_pending?: boolean } | undefined)
      : undefined
    const rs = draft?.review_status ?? ''
    const paid = !!draft?.paid
    // A card payment is approved instantly; a bank-slip payment sits here
    // ("paid") pending a coordinator's verification before it counts as approved.
    const paidSubmitted = paid || !!draft?.slip_pending
    const l3 = ['pending_l2', 'pending_l1', 'rejected_l2', 'locked'].includes(rs)
    const l2 = ['pending_l1', 'locked'].includes(rs)
    const l1 = rs === 'locked'

    // Show WHO the assigned technical officer is, e.g.
    // "Technical officer assigned (Kamal Fernando - TO005)".
    let toLabel = 'Technical officer assigned'
    if (toAssigned) {
      const t = (await this.db.query(
        `SELECT u.first_name, u.last_name, u.user_id
           FROM valuations v JOIN users u ON u.user_id = v.technical_officer_id
          WHERE v.project_id = $1 AND v.technical_officer_id <> ''
          ORDER BY v.valuation_id DESC LIMIT 1`,
        [projectId],
      )).rows[0] as { first_name?: string; last_name?: string; user_id?: string } | undefined
      if (t) toLabel = `Technical officer assigned (${`${t.first_name ?? ''} ${t.last_name ?? ''}`.trim()} - ${t.user_id})`
    }

    const labels = [
      'Applicant registered', 'Project created', 'Valuation requested',
      toLabel, 'Site inspected', 'Draft report created', 'Approved by L3',
      'Approved by L2', 'Approved by L1', 'Final report created',
      'Payment made', 'Payment approved', 'Report sent to client',
    ]
    const done = [
      applicant, true, hasValuation, toAssigned, !!inspection, !!draft, l3,
      l2, l1, l1, paidSubmitted, paid, paid,
    ]
    const currentIdx = done.findIndex((d) => !d)
    return {
      steps: labels.map((label, i) => ({
        label,
        state: (done[i] ? 'done' : i === currentIdx ? 'current' : 'waiting') as 'done' | 'current' | 'waiting',
      })),
    }
  }

  // Timeline for a specific valuation (by its surrogate row id).
  async timeline(rowId: string) {
    const n = Number(rowId)
    if (!Number.isInteger(n)) return null
    const vr = await this.db.query(
      `SELECT v.technical_officer_id, v.project_id, p.applicant_nic
         FROM valuations v JOIN projects p ON p.project_id = v.project_id
        WHERE v.id = $1 LIMIT 1`,
      [n],
    )
    const v = vr.rows[0]
    if (!v) return null
    return this.computeSteps(v.project_id as string, v.applicant_nic as string, true, !!v.technical_officer_id)
  }

  // Timeline for a project (works even with no valuations yet).
  async projectTimeline(projectId: string) {
    const id = (projectId ?? '').trim()
    const pr = await this.db.query(`SELECT applicant_nic FROM projects WHERE project_id = $1 LIMIT 1`, [id])
    if (!pr.rows[0]) return null
    const vr = await this.db.query(
      `SELECT technical_officer_id FROM valuations WHERE project_id = $1 ORDER BY valuation_id DESC LIMIT 1`,
      [id],
    )
    const latest = vr.rows[0]
    return this.computeSteps(id, pr.rows[0].applicant_nic as string, !!latest, !!latest?.technical_officer_id)
  }

  // Status detail for one valuation (looked up by its surrogate id, since the
  // valuation_id number is only unique within a project).
  async getStatus(rowId: string) {
    const n = Number(rowId)
    if (!Number.isInteger(n)) return null
    const r = await this.db.query(
      `SELECT v.id, v.valuation_id, v.project_id, v.status AS valuation_status, v.created_at,
              p.applicant_nic, p.property_type, p.status AS project_status
         FROM valuations v
         JOIN projects p ON p.project_id = v.project_id
        WHERE v.id = $1
        LIMIT 1`,
      [n],
    )
    const row = r.rows[0]
    if (!row) return null
    return {
      rowId: Number(row.id),
      valuationId: Number(row.valuation_id),
      projectId: row.project_id as string,
      nic: row.applicant_nic as string,
      propertyType: row.property_type as string,
      valuationStatus: row.valuation_status as string,
      projectStatus: row.project_status as string,
      createdAt: row.created_at as string,
    }
  }
}
